name: Build and test

on: [push, pull_request]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Bootstrap
        run: ./bootstrap.sh
        shell: bash
      - name: Build
        run: ./build.sh
        shell: bash
